-- Deploy votolegal:0011-populate_party to pg
-- requires: 0010-candidate-address

BEGIN;

INSERT INTO party (acronym, name) VALUES ('PMDB', 'PARTIDO DO MOVIMENTO DEMOCRÁTICO BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PTB', 'PARTIDO TRABALHISTA BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PDT', 'PARTIDO DEMOCRÁTICO TRABALHISTA');
INSERT INTO party (acronym, name) VALUES ('PT', 'PARTIDO DOS TRABALHADORES');
INSERT INTO party (acronym, name) VALUES ('DEM', 'DEMOCRATAS');
INSERT INTO party (acronym, name) VALUES ('PCdoB', 'PARTIDO COMUNISTA DO BRASIL');
INSERT INTO party (acronym, name) VALUES ('PSB', 'PARTIDO SOCIALISTA BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PSDB', 'PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA');
INSERT INTO party (acronym, name) VALUES ('PTC', 'PARTIDO TRABALHISTA CRISTÃO');
INSERT INTO party (acronym, name) VALUES ('PSC', 'PARTIDO SOCIAL CRISTÃO');
INSERT INTO party (acronym, name) VALUES ('PMN', 'PARTIDO DA MOBILIZAÇÃO NACIONAL');
INSERT INTO party (acronym, name) VALUES ('PRP', 'PARTIDO REPUBLICANO PROGRESSISTA');
INSERT INTO party (acronym, name) VALUES ('PPS', 'PARTIDO POPULAR SOCIALISTA');
INSERT INTO party (acronym, name) VALUES ('PV', 'PARTIDO VERDE');
INSERT INTO party (acronym, name) VALUES ('PTdoB', 'PARTIDO TRABALHISTA DO BRASIL');
INSERT INTO party (acronym, name) VALUES ('PP', 'PARTIDO PROGRESSISTA');
INSERT INTO party (acronym, name) VALUES ('PSTU', 'PARTIDO SOCIALISTA DOS TRABALHADORES UNIFICADO');
INSERT INTO party (acronym, name) VALUES ('PCB', 'PARTIDO COMUNISTA BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PRTB', 'PARTIDO RENOVADOR TRABALHISTA BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PHS', 'PARTIDO HUMANISTA DA SOLIDARIEDADE');
INSERT INTO party (acronym, name) VALUES ('PSDC', 'PARTIDO SOCIAL DEMOCRATA CRISTÃO');
INSERT INTO party (acronym, name) VALUES ('PCO', 'PARTIDO DA CAUSA OPERÁRIA');
INSERT INTO party (acronym, name) VALUES ('PTN', 'PARTIDO TRABALHISTA NACIONAL');
INSERT INTO party (acronym, name) VALUES ('PSL', 'PARTIDO SOCIAL LIBERAL');
INSERT INTO party (acronym, name) VALUES ('PRB', 'PARTIDO REPUBLICANO BRASILEIRO');
INSERT INTO party (acronym, name) VALUES ('PSOL', 'PARTIDO SOCIALISMO E LIBERDADE');
INSERT INTO party (acronym, name) VALUES ('PR', 'PARTIDO DA REPÚBLICA');
INSERT INTO party (acronym, name) VALUES ('PSD', 'PARTIDO SOCIAL DEMOCRÁTICO');
INSERT INTO party (acronym, name) VALUES ('PPL', 'PARTIDO PÁTRIA LIVRE');
INSERT INTO party (acronym, name) VALUES ('PEN', 'PARTIDO ECOLÓGICO NACIONAL');
INSERT INTO party (acronym, name) VALUES ('PROS', 'PARTIDO REPUBLICANO DA ORDEM SOCIAL');
INSERT INTO party (acronym, name) VALUES ('SD', 'SOLIDARIEDADE');
INSERT INTO party (acronym, name) VALUES ('NOVO', 'PARTIDO NOVO');
INSERT INTO party (acronym, name) VALUES ('REDE', 'REDE SUSTENTABILIDADE');
INSERT INTO party (acronym, name) VALUES ('PMB', 'PARTIDO DA MULHER BRASILEIRA');

COMMIT;
