#!/usr/bin/env perl
package VotoLegal::Daemon::Emailsd;
use common::sense;
use FindBin qw($RealBin $Script);
use lib "$RealBin/../../lib";

use AnyEvent;
use Config::General;
use Daemon::Generic;


BEGIN {
    use VotoLegal::SchemaConnected qw/load_envs_via_dbi get_schema/;
    load_envs_via_dbi();

    require VotoLegal::Logger;

}

use VotoLegal::Worker::Email;

our $verbose = 0;

newdaemon(
    options => {
        'verbose!' => \$verbose,
    },
    pidfile => "/tmp/Votolegal_$Script.pid",
);

sub gd_preconfig {
    my $self = shift;

    $0 = "VotoLegal::Daemon::Emailsd";
    $|++;

    return ();
}

sub gd_run {
    my $self = shift;

    my $cv = AnyEvent->condvar;

    my $worker = VotoLegal::Worker::Email->new(
        schema => get_schema(),
        logger => VotoLegal::Logger::get_logger(),

    );

    my $w = AnyEvent->timer(
        after    => 0.0,
        interval => $worker->timer,
        cb       => sub { $worker->listen_queue() },
    );

    $cv->recv;
}

1;

